doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/User/Model'
                prefix: 'Domain\User\Model'
                alias: App
            Session:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/User/Model'
                prefix: 'Domain\User\Model'
                alias: App
            Declaration:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Declaration/Model'
                prefix: 'Domain\Declaration\Model'
                alias: App
